"""Versioned KerOp → SpecInv forward-spectrum artifact.

KerOp learns a *forward* operator and can export its spectrum.  SpecInv consumes
that spectrum as the singular values of a compact inverse problem and learns a
spectral filter.  This module is the contract between the two: a small, versioned
``npz`` / ``json`` payload — not a new theorem and not a substitute for either
repository's own bar.

Schema ``kerop.specinv.spectrum/v1``
------------------------------------
Required fields (see ``docs/KEROP_SPECTRUM.md``):

* ``eigenvalues`` — 1-D positive, non-increasing forward spectrum used as
  SpecInv singular values (KerOp input-mode weights, or a 1-D RF spectrum)
* ``operator_id`` — stable id of the KerOp instance that produced the array
* ``seed`` — KerOp model seed
* ``n`` — number of exported modes
* ``feature_count`` — random-feature count ``M`` attached to this export

The payload may also carry the flattened product-set RF spectrum, the
``(r, b)`` pair, and the implied ill-posedness ``p = 1/b``.

This module can *write* an artifact only by importing KerOp and calling
``SpectralOperatorModel``.  A committed fixture is allowed as a load path, but
it must have been generated by :func:`export_kerop_spectrum`.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType
from typing import Any

import numpy as np
from numpy.typing import NDArray

from .operators import DiagonalSpectralOperator

__all__ = [
    "ARTIFACT_SCHEMA",
    "ARTIFACT_VERSION",
    "DEFAULT_OPERATOR_ID_PREFIX",
    "JOINT_B",
    "JOINT_FEATURE_N_REF",
    "JOINT_N_MODES",
    "JOINT_OUTPUT_DIM",
    "JOINT_R",
    "JOINT_SEED",
    "JointPathError",
    "SpectrumArtifact",
    "candidate_kerop_roots",
    "default_fixture_path",
    "estimate_ill_posedness",
    "export_kerop_spectrum",
    "fingerprint",
    "import_kerop",
    "load_spectrum_artifact",
    "operator_from_artifact",
    "require_kerop",
    "write_spectrum_artifact",
]

FloatArray = NDArray[np.float64]

ARTIFACT_SCHEMA = "kerop.specinv.spectrum/v1"
ARTIFACT_VERSION = 1
DEFAULT_OPERATOR_ID_PREFIX = "kerop.spectral"

# Shared joint instance: KerOp SpectralOperatorModel with b = 2/3 so the
# input-mode weights are sigma_n = n^{-3/2}, which is the section 5.1 spectrum
# SpecInv already measures.  output_dim=6 keeps the KerOp matched-risk
# comparison in the same operator-valued regime as KerOp's published spectral
# wall-time run.
JOINT_R = 0.5
JOINT_B = 2.0 / 3.0
JOINT_N_MODES = 2048
JOINT_OUTPUT_DIM = 6
JOINT_SEED = 20260301
JOINT_FEATURE_N_REF = 600


class JointPathError(RuntimeError):
    """The KerOp → SpecInv path cannot be used as specified."""


@dataclass(frozen=True)
class SpectrumArtifact:
    """A KerOp forward-spectrum payload SpecInv can invert."""

    schema: str
    schema_version: int
    operator_id: str
    seed: int
    n: int
    feature_count: int
    eigenvalues: FloatArray
    r: float
    b: float
    output_dim: int
    ill_posedness: float
    source: str = "kerop.SpectralOperatorModel"
    kerop_version: str | None = None
    rf_spectrum: FloatArray | None = None
    extra: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        values = np.asarray(self.eigenvalues, dtype=np.float64).reshape(-1)
        if values.size == 0:
            raise ValueError("eigenvalues must be non-empty")
        if np.any(~np.isfinite(values)) or np.any(values <= 0.0):
            raise ValueError("eigenvalues must be finite and strictly positive")
        if np.any(np.diff(values) > 1e-12):
            raise ValueError("eigenvalues must be non-increasing")
        if int(self.n) != values.size:
            raise ValueError(f"n={self.n} does not match eigenvalues length {values.size}")
        if self.feature_count < 1:
            raise ValueError("feature_count must be >= 1")
        if self.schema != ARTIFACT_SCHEMA:
            raise ValueError(f"unsupported schema {self.schema!r}")
        if self.schema_version != ARTIFACT_VERSION:
            raise ValueError(f"unsupported schema_version {self.schema_version}")
        object.__setattr__(self, "eigenvalues", values)
        if self.rf_spectrum is not None:
            rf = np.asarray(self.rf_spectrum, dtype=np.float64).reshape(-1)
            object.__setattr__(self, "rf_spectrum", rf)

    def metadata(self) -> dict[str, Any]:
        """JSON-safe header (no coefficient arrays)."""
        payload = {
            "schema": self.schema,
            "schema_version": self.schema_version,
            "operator_id": self.operator_id,
            "seed": int(self.seed),
            "n": int(self.n),
            "feature_count": int(self.feature_count),
            "r": float(self.r),
            "b": float(self.b),
            "output_dim": int(self.output_dim),
            "ill_posedness": float(self.ill_posedness),
            "source": self.source,
            "kerop_version": self.kerop_version,
            "fingerprint": fingerprint(self),
        }
        payload.update(self.extra)
        return payload


def estimate_ill_posedness(eigenvalues: FloatArray, fit_modes: int | None = None) -> float:
    """Least-squares :math:`p` in :math:`\\sigma_n \\propto n^{-p}` on the leading modes."""
    values = np.asarray(eigenvalues, dtype=np.float64).reshape(-1)
    if values.size < 4:
        raise ValueError("need at least 4 eigenvalues to estimate p")
    width = values.size if fit_modes is None else min(int(fit_modes), values.size)
    width = max(width, 4)
    ranks = np.arange(1, width + 1, dtype=np.float64)
    slope = float(np.polyfit(np.log(ranks), np.log(values[:width]), 1)[0])
    return float(-slope)


def fingerprint(artifact: SpectrumArtifact) -> str:
    """Short stable hash of schema + operator id + seed + eigenvalues."""
    digest = hashlib.sha256()
    digest.update(artifact.schema.encode("utf-8"))
    digest.update(artifact.operator_id.encode("utf-8"))
    digest.update(str(int(artifact.seed)).encode("utf-8"))
    digest.update(np.ascontiguousarray(artifact.eigenvalues).tobytes())
    return digest.hexdigest()[:16]


def candidate_kerop_roots(explicit: str | Path | None = None) -> list[Path]:
    """Ordered places a KerOp checkout might live."""
    roots: list[Path] = []
    if explicit is not None:
        roots.append(Path(explicit).expanduser().resolve())
    env = os.environ.get("KEROP_ROOT")
    if env:
        roots.append(Path(env).expanduser().resolve())
    here = Path(__file__).resolve()
    cwd = Path.cwd().resolve()
    for base in (
        cwd,
        cwd.parent,
        here.parents[2],
        here.parents[3] if len(here.parents) > 3 else cwd,
    ):
        roots.append(base / "KerOp")
        roots.append(base / "kerop")
    # De-duplicate while keeping order.
    seen: set[Path] = set()
    unique: list[Path] = []
    for path in roots:
        if path in seen:
            continue
        seen.add(path)
        unique.append(path)
    return unique


def import_kerop(kerop_root: str | Path | None = None) -> ModuleType:
    """Import ``kerop``, adding a sibling checkout's ``src/`` to ``sys.path`` if needed."""
    try:
        import kerop as installed

        return installed
    except ImportError:
        pass
    for root in candidate_kerop_roots(kerop_root):
        src = root / "src"
        if (src / "kerop" / "__init__.py").is_file():
            src_s = str(src)
            if src_s not in sys.path:
                sys.path.insert(0, src_s)
            import kerop as sibling

            return sibling
    raise JointPathError(
        "kerop is not importable. The joint path requires KerOp "
        "(https://github.com/amineux/KerOp): install it, pass --kerop-root, "
        "set KEROP_ROOT, or place a checkout next to SpecInv. "
        "This is a FAIL, not a joint result — the old 1D suite will not be substituted."
    )


def require_kerop(kerop_root: str | Path | None = None) -> ModuleType:
    """Alias of :func:`import_kerop` for call sites that want the hard fail."""
    return import_kerop(kerop_root)


def _operator_id(r: float, b: float, n_modes: int, output_dim: int, seed: int) -> str:
    return (
        f"{DEFAULT_OPERATOR_ID_PREFIX}/v1"
        f":r={r:g}:b={b:.10g}:n={n_modes}:dv={output_dim}:seed={seed}"
    )


def export_kerop_spectrum(
    *,
    n_modes: int = JOINT_N_MODES,
    r: float = JOINT_R,
    b: float = JOINT_B,
    output_dim: int = JOINT_OUTPUT_DIM,
    seed: int = JOINT_SEED,
    feature_count: int | None = None,
    kerop_root: str | Path | None = None,
) -> SpectrumArtifact:
    """Build the joint artifact by constructing KerOp's ``SpectralOperatorModel``.

    The 1-D array SpecInv inverts is the input-mode weight sequence
    :math:`\\mu_j = j^{-1/b}`.  With the default :math:`b=2/3` this is exactly
    :math:`n^{-3/2}`, the §5.1 spectrum.  The flattened product-set
    :math:`\\{\\mu_j\\nu_k\\}` is stored as ``rf_spectrum`` so the KerOp bar can
    be checked on the same instance.
    """
    kerop = require_kerop(kerop_root)
    from kerop.data.spectral import SpectralOperatorModel
    from kerop.theory import features_required

    model = SpectralOperatorModel(r=r, b=b, n_modes=n_modes, output_dim=output_dim, seed=seed)
    mode_weights = np.asarray(model.mode_weights, dtype=np.float64)
    # Already non-increasing: j^{-1/b}.
    rf_spectrum = np.sort(np.asarray(model.eigenvalues, dtype=np.float64).reshape(-1))[::-1]
    if feature_count is None:
        feature_count = int(features_required(JOINT_FEATURE_N_REF, r, b, n_summands=1))
        feature_count = max(feature_count, math.ceil(math.sqrt(JOINT_FEATURE_N_REF)))
    return SpectrumArtifact(
        schema=ARTIFACT_SCHEMA,
        schema_version=ARTIFACT_VERSION,
        operator_id=_operator_id(r, b, n_modes, output_dim, seed),
        seed=int(seed),
        n=int(mode_weights.size),
        feature_count=int(feature_count),
        eigenvalues=mode_weights,
        r=float(r),
        b=float(b),
        output_dim=int(output_dim),
        ill_posedness=float(1.0 / b),
        source="kerop.SpectralOperatorModel",
        kerop_version=str(getattr(kerop, "__version__", "unknown")),
        rf_spectrum=rf_spectrum,
        extra={
            "n_summands": 1,
            "feature_n_ref": JOINT_FEATURE_N_REF,
            "generated_by": "specinv.spectrum_contract.export_kerop_spectrum",
        },
    )


def write_spectrum_artifact(path: str | Path, artifact: SpectrumArtifact) -> Path:
    """Write ``artifact`` as ``.npz`` (arrays + JSON header) and a sibling ``.json``."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = artifact.metadata()
    np.savez(
        path,
        eigenvalues=artifact.eigenvalues,
        rf_spectrum=(
            artifact.rf_spectrum
            if artifact.rf_spectrum is not None
            else np.asarray([], dtype=np.float64)
        ),
        meta=np.asarray(json.dumps(header, sort_keys=True)),
    )
    json_path = path.with_suffix(".json")
    # JSON carries the 1-D spectrum SpecInv inverts plus the header. The
    # flattened RF product-set stays in the npz — it is large and unused by
    # the inverse-problem side.
    json_payload = {
        **header,
        "eigenvalues": artifact.eigenvalues.tolist(),
        "has_rf_spectrum": artifact.rf_spectrum is not None,
    }
    json_path.write_text(json.dumps(json_payload, indent=2) + "\n")
    return path


def _from_mapping(payload: dict[str, Any]) -> SpectrumArtifact:
    if "eigenvalues" not in payload and "rf_spectrum" in payload:
        values = np.asarray(payload["rf_spectrum"], dtype=np.float64).reshape(-1)
        values = np.sort(values)[::-1]
    else:
        values = np.asarray(payload["eigenvalues"], dtype=np.float64).reshape(-1)
    rf = payload.get("rf_spectrum")
    n = int(payload.get("n", values.size))
    ill = payload.get("ill_posedness")
    b = float(payload.get("b", JOINT_B))
    if ill is None:
        ill = 1.0 / b if b > 0.0 else estimate_ill_posedness(values)
    extra_keys = {
        "schema",
        "schema_version",
        "operator_id",
        "seed",
        "n",
        "feature_count",
        "eigenvalues",
        "r",
        "b",
        "output_dim",
        "ill_posedness",
        "source",
        "kerop_version",
        "rf_spectrum",
        "fingerprint",
    }
    extra = {k: v for k, v in payload.items() if k not in extra_keys}
    return SpectrumArtifact(
        schema=str(payload.get("schema", ARTIFACT_SCHEMA)),
        schema_version=int(payload.get("schema_version", ARTIFACT_VERSION)),
        operator_id=str(payload["operator_id"]),
        seed=int(payload["seed"]),
        n=n,
        feature_count=int(payload["feature_count"]),
        eigenvalues=values,
        r=float(payload.get("r", JOINT_R)),
        b=b,
        output_dim=int(payload.get("output_dim", 1)),
        ill_posedness=float(ill),
        source=str(payload.get("source", "kerop.SpectralOperatorModel")),
        kerop_version=payload.get("kerop_version"),
        rf_spectrum=None if rf is None else np.asarray(rf, dtype=np.float64),
        extra=extra,
    )


def load_spectrum_artifact(path: str | Path) -> SpectrumArtifact:
    """Load a ``v1`` artifact from ``.npz`` or ``.json``."""
    path = Path(path)
    if not path.is_file():
        raise JointPathError(f"KerOp spectrum artifact not found: {path}")
    suffix = path.suffix.lower()
    if suffix == ".json":
        payload = json.loads(path.read_text())
        if not isinstance(payload, dict):
            raise JointPathError("spectrum JSON must be an object")
        return _from_mapping(payload)
    if suffix != ".npz":
        raise JointPathError(f"spectrum artifact must be .npz or .json, got {path}")
    with np.load(path, allow_pickle=False) as data:
        meta_raw = data["meta"].item() if "meta" in data.files else "{}"
        header = json.loads(str(meta_raw))
        header["eigenvalues"] = np.asarray(data["eigenvalues"], dtype=np.float64)
        if "rf_spectrum" in data.files:
            rf = np.asarray(data["rf_spectrum"], dtype=np.float64)
            header["rf_spectrum"] = rf if rf.size else None
        return _from_mapping(header)


def operator_from_artifact(
    artifact: SpectrumArtifact, n_modes: int | None = None
) -> DiagonalSpectralOperator:
    """Turn the exported 1-D spectrum into a SpecInv diagonal operator."""
    width = artifact.n if n_modes is None else int(n_modes)
    if width < 1 or width > artifact.n:
        raise ValueError(f"n_modes must lie in [1, {artifact.n}], got {width}")
    return DiagonalSpectralOperator(artifact.eigenvalues[:width].copy(), artifact.ill_posedness)


def default_fixture_path() -> Path:
    """Committed contract fixture shipped with this repository."""
    repo = Path(__file__).resolve().parents[2] / "fixtures" / "kerop_spectrum_v1.npz"
    if repo.is_file():
        return repo
    packaged = Path(__file__).resolve().parent / "data" / "kerop_spectrum_v1.npz"
    return packaged


def main(argv: list[str] | None = None) -> int:
    """Write a KerOp spectrum artifact (requires KerOp)."""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        type=Path,
        default=Path("fixtures/kerop_spectrum_v1.npz"),
        help="destination .npz (a sibling .json is also written)",
    )
    parser.add_argument("--kerop-root", type=Path, default=None)
    parser.add_argument("--n-modes", type=int, default=JOINT_N_MODES)
    parser.add_argument("--seed", type=int, default=JOINT_SEED)
    args = parser.parse_args(argv)
    artifact = export_kerop_spectrum(
        n_modes=args.n_modes, seed=args.seed, kerop_root=args.kerop_root
    )
    written = write_spectrum_artifact(args.write, artifact)
    print(f"wrote {written}")
    print(f"wrote {written.with_suffix('.json')}")
    print(f"operator_id={artifact.operator_id}")
    print(f"fingerprint={fingerprint(artifact)}")
    print(f"n={artifact.n}  p={artifact.ill_posedness:.6g}  M={artifact.feature_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
